from anndata import AnnData
from block.block_interface import Block
import codecs
import io
from joblib import parallel_backend
from matplotlib import pyplot as plt
import scanpy as sc
from threadpoolctl import threadpool_limits


class PCA(Block):

    """
    `PCA` subclass, which inherits from the `Block` superclass.
    """

    required_parameters = []
    """The parameters required by a `PCA` block."""

    def __init__(self):
        """Initialise a `PCA` object."""
        super().__init__()

    def validate_parameters(self, parameters: dict) -> None:
        """
        Validates that all of the parameters in the `required_parameters` attribute are present in the parameters dictionary. The implementation is inherited from the `Block` superclass.

        Parameters:

            - `parameters`: A dictionary mapping block parameters to their values.
        """
        super(PCA, self).validate_parameters(parameters)

    def run(self, adata: AnnData, parameters: dict) -> (AnnData, dict):
        """
        Execute the code for a `PCA` block.

        Calculates QC metrics, scales the data, carries out PCA and plots the variance ratio.

        Parameters:

            - `adata`: The AnnData for which the code should be executed.
            - `parameters`: A dictionary mapping parameter names to their values, which should be used while executing the code.

        Return:

            - The resulting AnnData after performing the block's behaviour.
            - A dictionary containing the results that will be seen by the user.
        """
        self.validate_parameters(parameters)

        adata.var["mt"] = adata.var_names.str.startswith("MT-")
        sc.pp.calculate_qc_metrics(adata, qc_vars=["mt"], percent_top=None, log1p=False, inplace=True)
        adata.obs["total_UMIs"] = adata.obs["total_counts"]
        adata.obs = adata.obs.drop("total_counts", axis=1)

        # Consider adding Regress Out PCA step (see Trello)
        # sc.pp.regress_out(adata, ["total_UMIs", "pct_counts_mt"], n_jobs=1)

        with parallel_backend("threading", n_jobs=1):
            with threadpool_limits(limits=1, user_api="blas"):
                sc.pp.scale(adata, max_value=10)
                sc.tl.pca(adata, svd_solver="arpack")
        sc.pl.pca_variance_ratio(adata, log=True)
        plt.ylabel("log variance ratio")

        image_stream = io.BytesIO()
        plt.savefig(image_stream, format="png")
        image_stream.seek(0)
        image = {
            "image": str(codecs.encode(image_stream.read(), "base64")),
            "alt_text": "A scatter plot displaying the contribution of each PC to the total variance in the data, generated by a Principal Component Analysis block"
        }
        message = {
            "image": image
        }
        return adata, message
