name: scampi-generate-covid-dataset
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.4.1
  - r-seurat=5.1.0
  - python=3.11
  - pip=23.3
  - pip:
      - scanpy==1.9.6
      - pandas==2.0.3
      - numpy==1.26.4