name: scampi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.3
  - pip:
      - anndata==0.9.2
      - bidict==0.23.1
      - blinker==1.7.0
      - cachelib==0.9.0
      - cffi==1.16.0
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.1.1
      - coverage==7.4.0
      - cycler==0.12.1
      - exceptiongroup==1.2.0
      - flake8==7.0.0
      - flask==3.0.0
      - flask-caching==2.1.0
      - flask-cors==4.0.0
      - flask-socketio==5.3.6
      - fonttools==4.44.0
      - get-annotations==0.1.2
      - gevent==24.2.1
      - gevent-websocket==0.10.1
      - greenlet==3.0.3
      - h11==0.14.0
      - h5py==3.10.0
      - harmonypy=0.0.10
      - harmony-pytorch=0.1.8
      - igraph==0.11.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - iniconfig==2.0.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - leidenalg==0.10.2
      - llvmlite==0.41.1
      - markupsafe==2.1.3
      - matplotlib==3.7.3
      - mccabe==0.7.0
      - natsort==8.4.0
      - networkx==3.1
      - numba==0.58.1
      - numpy==1.24.4
      - packaging==23.2
      - pandas==2.0.3
      - patsy==0.5.3
      - pep8==1.7.1
      - pillow==10.1.0
      - pluggy==1.3.0
      - pycodestyle==2.11.1
      - pycparser==2.21
      - pyflakes==3.2.0
      - pynndescent==0.5.10
      - pyparsing==3.1.1
      - pytest==7.4.4
      - pytest-cov==4.1.0
      - python-dateutil==2.8.2
      - python-engineio==4.9.1
      - python-socketio==5.11.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - scanpy==1.9.6
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - session-info==1.0.0
      - simple-websocket==1.0.0
      - six==1.16.0
      - statsmodels==0.14.0
      - stdlib-list==0.9.0
      - texttable==1.7.0
      - threadpoolctl==3.2.0
      - tomli==2.0.1
      - tqdm==4.66.1
      - tzdata==2023.3
      - umap-learn==0.5.4
      - uuid==1.30
      - werkzeug==3.0.1
      - wsproto==1.2.0
      - zipp==3.17.0
      - zope-event==5.0
      - zope-interface==6.2
      - celery[redis]
      - requests
      - websocket-client