name: visual-bioinformatics
channels:
  - defaults
dependencies:
  - pip=23.3=py38h06a4308_0
  - pip:
      - anndata==0.9.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.44.0
      - get-annotations==0.1.2
      - h5py==3.10.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - llvmlite==0.41.1
      - matplotlib==3.7.3
      - natsort==8.4.0
      - networkx==3.1
      - numba==0.58.1
      - numpy==1.24.4
      - pandas==2.0.3
      - patsy==0.5.3
      - pillow==10.1.0
      - pynndescent==0.5.10
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - scanpy==1.9.6
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - session-info==1.0.0
      - six==1.16.0
      - statsmodels==0.14.0
      - stdlib-list==0.9.0
      - threadpoolctl==3.2.0
      - tzdata==2023.3
      - umap-learn==0.5.4
      - uuid==1.30
      - zipp==3.17.0
