on:
  [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -el {0}
        working-directory: back-end
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: scampi
          environment-file: back-end/environment.yml
          auto-activate-base: false
      - name: Backend Tests
        run: |
          conda info
          conda list
          flake8 --ignore=E501 app
          cd app
          python -m pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
#          need to move test results back up a level for detection?