on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -el {0}
        working-directory: back-end
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: visual-bioinformatics
          environment-file: back-end/environment.yml
          python-version: 3.8
          auto-activate-base: false
      - shell: bash
        run: |
          conda info
          conda list
      - name: Run pytest
        shell: bash
        run: |
          conda install pip
          pip install Flask
          pip install Flask-Cors
          pip install scanpy
          pip install scipy
          pip install pytest
          pip install pytest pytest-cov
          pytest test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
