on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: back-end
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.0'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install flask
          pip install scanpy
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
          
