on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -el {0}
        working-directory: back-end
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: visual-bioinformatics
          environment-file: back-end/environment.yml
          python-version: 3.8
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - name: Run pytest
        shell: bash
        run: |
          pytest test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
